# Generated by Django 5.0.6 on 2024-06-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("score", models.IntegerField(default=0, null=True)),
                ("dateJoined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
